### ISSUE TITLE
[IllegalStateException] Test not setup properly. Use a ComposeTestRule in your test to be able to interact with composables

### ISSUE THREAD

**Issue by Viacheslav-Romanov** [open-tool/ultron#85] opened 2024-08-03 13:15 UTC
Adding withTimeout to lazy initiated page elements causing IllegalStateException. If we overwrite ComposeElementsPage in the sample app the following way:

```kotlin
object ComposeElementsPage : Page<ComposeElementsPage>() {
    val status by lazy { hasTestTag(ComposeElementsActivity.Constants.statusText).withTimeout(10_000) }
    val likesCounter by lazy { hasTestTag(likesCounterButton).withTimeout(10_000) }
    val longAndDoubleClickButton by lazy { hasTestTag(clickListenerButton).withTimeout(10_000) }
    val regionsNode by lazy { hasTestTag(RegionsClickListenerTestTags.regionsNode).withTimeout(10_000) }
    val clickedRegion by lazy { hasTestTag(RegionsClickListenerTestTags.regionsClickedText).withTimeout(10_000) }
    val editableText by lazy { hasTestTag(ComposeElementsActivity.editableText).withTimeout(10_000) }
    val swipeableNode by lazy { hasTestTag(ComposeElementsActivity.swipeableNode).withTimeout(10_000) }
    val disabledButton by lazy { hasTestTag(ComposeElementsActivity.disabledButton).withTimeout(10_000) }
    val simpleCheckbox by lazy { hasTestTag(ComposeElementsActivity.simpleCheckbox).withTimeout(10_000) }
    val progressBar by lazy { hasTestTag(ComposeElementsActivity.progressBar).withTimeout(10_000) }
    val maleRadioButton by lazy { hasTestTag(radioButtonMaleTestTag).withTimeout(10_000) }
    val femaleRadioButton by lazy { hasTestTag(radioButtonFemaleTestTag).withTimeout(10_000) }
    val notExistedElement by lazy { hasTestTag("NotExistedTestTag").withTimeout(10_000) }
}
```

import proper action extensions and then run ComposeUIElementsTest, most of the tests will fail with:

<img width="1328" alt="image" src="https://github.com/user-attachments/assets/a74f4870-6224-4297-b2e5-a90f9726b910">

**Comment by alex-tiurin** [comment] 2024-08-06 19:43
Root cause found, will be fixed soon

**Comment by alex-tiurin** [comment] 2024-08-07 20:20
Fixed in https://github.com/open-tool/ultron/releases/tag/2.5.0-alpha15

**Closed by alex-tiurin** 2024-08-07 20:20 UTC
Labels: bug
