### ISSUE TITLE
Detailed allure report did not stop allure step for operation with assertion

### ISSUE THREAD

**Issue by dabrynskiy** [open-tool/ultron#89] opened 2024-09-03 09:28 UTC
ultron-allure  2.5.0-alpha14
com.atiurin.ultron.allure.config.UltronAllureConfig.params.detailedAllureReport = true
this parameter added listener - instance DetailedOperationAllureListener()

DetailedOperationAllureListener for each operation:

- create allure step and store step uuid in property `lateinit var uuid: String`
- update step status using step uuid
- stop step using uuid

But it does not work correctly for operation with assertion, for example:
`.withAssertion("example assertion") { hasText("123") }.replaceText("123")`

listener DetailedOperationAllureListener() in this case:

- created allure step for action `replaceText("123")`
- created allure step for assertion `hasText("123")` (when ultron create new step uuid previous step lost)
- update step status for assertion `hasText("123")`
- stop step for assertion `hasText("123")`

allure step for action `replaceText("123")` did not stop and have status "unknown"
<img width="1149" alt="image" src="https://github.com/user-attachments/assets/86ad4a6d-20ec-4488-979f-ac0cb15f401f">

**Comment by alex-tiurin** [comment] 2024-09-18 20:14
Couldn't reproduce a bug for a while. Give me little bit more time for research. In case i find it, i will fix it in next release. 
Thank you.

**Comment by dabrynskiy** [comment] 2024-09-23 17:09
> Couldn't reproduce a bug for a while. Give me little bit more time for research. In case i find it, i will fix it in next release. Thank you.

Hi!
sorry, incorrect example
check please `.withAssertion("example assertion", isListened = true) { hasText("123") }.replaceText("123")`

**Comment by alex-tiurin** [comment] 2024-09-29 18:30
Fixed https://github.com/open-tool/ultron/pull/91

soon it will be released

**Closed** 2024-09-30 18:49 UTC
Labels: bug

**Comment by alex-tiurin** [comment] 2024-09-30 18:55
[Released ](https://github.com/open-tool/ultron/releases/tag/2.5.0-alpha16)
